services:
  api:
    build:
      context: ./api       # contexto = pasta api
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-projeto}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-projeto}
      POSTGRES_DB: ${DATABASE_NAME:-projeto}

